# Form implementation generated from reading ui file 'robotui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 694)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(100, 20, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.btn_pos_z_plus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_pos_z_plus.setGeometry(QtCore.QRect(160, 50, 81, 31))
        self.btn_pos_z_plus.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_pos_z_plus.setObjectName("btn_pos_z_plus")
        self.btn_pos_x_minus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_pos_x_minus.setGeometry(QtCore.QRect(260, 50, 81, 31))
        self.btn_pos_x_minus.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_pos_x_minus.setObjectName("btn_pos_x_minus")
        self.btn_pos_home = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_pos_home.setGeometry(QtCore.QRect(160, 90, 81, 31))
        self.btn_pos_home.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_pos_home.setObjectName("btn_pos_home")
        self.btn_pos_x_plus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_pos_x_plus.setGeometry(QtCore.QRect(60, 130, 81, 31))
        self.btn_pos_x_plus.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_pos_x_plus.setObjectName("btn_pos_x_plus")
        self.btn_pos_z_minus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_pos_z_minus.setGeometry(QtCore.QRect(160, 130, 81, 31))
        self.btn_pos_z_minus.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_pos_z_minus.setObjectName("btn_pos_z_minus")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 180, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btn_home = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_home.setGeometry(QtCore.QRect(100, 420, 81, 41))
        self.btn_home.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_home.setObjectName("btn_home")
        self.btn_setting = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_setting.setGeometry(QtCore.QRect(200, 420, 81, 41))
        self.btn_setting.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_setting.setObjectName("btn_setting")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 490, 441, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.table_tmatrix = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.table_tmatrix.setGeometry(QtCore.QRect(0, 520, 421, 121))
        self.table_tmatrix.setAutoScroll(True)
        self.table_tmatrix.setRowCount(4)
        self.table_tmatrix.setColumnCount(4)
        self.table_tmatrix.setObjectName("table_tmatrix")
        self.table_tmatrix.horizontalHeader().setVisible(False)
        self.table_tmatrix.horizontalHeader().setHighlightSections(False)
        self.table_tmatrix.horizontalHeader().setStretchLastSection(False)
        self.table_tmatrix.verticalHeader().setVisible(False)
        self.table_tmatrix.verticalHeader().setHighlightSections(False)
        self.table_tmatrix.verticalHeader().setStretchLastSection(False)
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 210, 348, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.line_j1_val = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.line_j1_val.setReadOnly(True)
        self.line_j1_val.setObjectName("line_j1_val")
        self.horizontalLayout.addWidget(self.line_j1_val)
        self.inc1 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.inc1.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.inc1.setObjectName("inc1")
        self.horizontalLayout.addWidget(self.inc1)
        self.des1 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.des1.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.des1.setObjectName("des1")
        self.horizontalLayout.addWidget(self.des1)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 240, 348, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.line_j2_val = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.line_j2_val.setReadOnly(True)
        self.line_j2_val.setObjectName("line_j2_val")
        self.horizontalLayout_2.addWidget(self.line_j2_val)
        self.inc2 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.inc2.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.inc2.setObjectName("inc2")
        self.horizontalLayout_2.addWidget(self.inc2)
        self.des2 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.des2.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.des2.setObjectName("des2")
        self.horizontalLayout_2.addWidget(self.des2)
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 270, 348, 30))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.line_j3_val = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.line_j3_val.setReadOnly(True)
        self.line_j3_val.setObjectName("line_j3_val")
        self.horizontalLayout_3.addWidget(self.line_j3_val)
        self.inc3 = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.inc3.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.inc3.setObjectName("inc3")
        self.horizontalLayout_3.addWidget(self.inc3)
        self.des3 = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.des3.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.des3.setObjectName("des3")
        self.horizontalLayout_3.addWidget(self.des3)
        self.layoutWidget3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(30, 300, 348, 30))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.line_j4_val = QtWidgets.QLineEdit(parent=self.layoutWidget3)
        self.line_j4_val.setReadOnly(True)
        self.line_j4_val.setObjectName("line_j4_val")
        self.horizontalLayout_4.addWidget(self.line_j4_val)
        self.inc4 = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.inc4.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.inc4.setObjectName("inc4")
        self.horizontalLayout_4.addWidget(self.inc4)
        self.des4 = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.des4.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.des4.setObjectName("des4")
        self.horizontalLayout_4.addWidget(self.des4)
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 360, 348, 30))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_16 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        self.line_j4_val_5 = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        self.line_j4_val_5.setReadOnly(True)
        self.line_j4_val_5.setObjectName("line_j4_val_5")
        self.horizontalLayout_10.addWidget(self.line_j4_val_5)
        self.inc6 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.inc6.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.inc6.setObjectName("inc6")
        self.horizontalLayout_10.addWidget(self.inc6)
        self.des6 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.des6.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.des6.setObjectName("des6")
        self.horizontalLayout_10.addWidget(self.des6)
        self.layoutWidget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 330, 348, 30))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_17 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_11.addWidget(self.label_17)
        self.line_j3_val_3 = QtWidgets.QLineEdit(parent=self.layoutWidget_3)
        self.line_j3_val_3.setReadOnly(True)
        self.line_j3_val_3.setObjectName("line_j3_val_3")
        self.horizontalLayout_11.addWidget(self.line_j3_val_3)
        self.inc5 = QtWidgets.QPushButton(parent=self.layoutWidget_3)
        self.inc5.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.inc5.setObjectName("inc5")
        self.horizontalLayout_11.addWidget(self.inc5)
        self.des5 = QtWidgets.QPushButton(parent=self.layoutWidget_3)
        self.des5.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.des5.setObjectName("des5")
        self.horizontalLayout_11.addWidget(self.des5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "POSITION CONTROL"))
        self.btn_pos_z_plus.setText(_translate("MainWindow", "↑ Z+"))
        self.btn_pos_x_minus.setText(_translate("MainWindow", "X- ↗"))
        self.btn_pos_home.setText(_translate("MainWindow", "O"))
        self.btn_pos_x_plus.setText(_translate("MainWindow", "X+ ↙"))
        self.btn_pos_z_minus.setText(_translate("MainWindow", "↓ Z-"))
        self.label_3.setText(_translate("MainWindow", "JOIN CONTROL"))
        self.btn_home.setText(_translate("MainWindow", "HOME"))
        self.btn_setting.setText(_translate("MainWindow", "SETTING"))
        self.label_2.setText(_translate("MainWindow", "HOMOGENEOUS TRANSFORMATION MATRICES"))
        self.label_5.setText(_translate("MainWindow", "Join 1"))
        self.inc1.setText(_translate("MainWindow", "INC ↑"))
        self.des1.setText(_translate("MainWindow", "DES ↓"))
        self.label_6.setText(_translate("MainWindow", "Join 2"))
        self.inc2.setText(_translate("MainWindow", "INC ↑"))
        self.des2.setText(_translate("MainWindow", "DES ↓"))
        self.label_7.setText(_translate("MainWindow", "Join 3"))
        self.inc3.setText(_translate("MainWindow", "INC ↑"))
        self.des3.setText(_translate("MainWindow", "DES ↓"))
        self.label_8.setText(_translate("MainWindow", "Join 4"))
        self.inc4.setText(_translate("MainWindow", "INC ↑"))
        self.des4.setText(_translate("MainWindow", "DES ↓"))
        self.label_16.setText(_translate("MainWindow", "Join 6"))
        self.inc6.setText(_translate("MainWindow", "INC ↑"))
        self.des6.setText(_translate("MainWindow", "DES ↓"))
        self.label_17.setText(_translate("MainWindow", "Join 5"))
        self.inc5.setText(_translate("MainWindow", "INC ↑"))
        self.des5.setText(_translate("MainWindow", "DES ↓"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
