# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1234, 864)
        self.centralwidget = QtWidgets.QWidget(parent=mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ZD = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ZD.setGeometry(QtCore.QRect(170, 50, 121, 51))
        self.ZD.setObjectName("ZD")
        self.XT = QtWidgets.QPushButton(parent=self.centralwidget)
        self.XT.setGeometry(QtCore.QRect(300, 50, 121, 51))
        self.XT.setObjectName("XT")
        self.XD = QtWidgets.QPushButton(parent=self.centralwidget)
        self.XD.setGeometry(QtCore.QRect(40, 170, 121, 51))
        self.XD.setObjectName("XD")
        self.ZT = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ZT.setGeometry(QtCore.QRect(170, 170, 121, 51))
        self.ZT.setObjectName("ZT")
        self.O = QtWidgets.QPushButton(parent=self.centralwidget)
        self.O.setGeometry(QtCore.QRect(170, 110, 121, 51))
        self.O.setObjectName("O")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(180, 10, 251, 31))
        self.textEdit.setObjectName("textEdit")
        self.donghoc = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.donghoc.setGeometry(QtCore.QRect(430, 320, 521, 201))
        self.donghoc.setObjectName("donghoc")
        self.donghoc.setColumnCount(4)
        self.donghoc.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.donghoc.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.donghoc.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.donghoc.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.donghoc.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.donghoc.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.donghoc.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.donghoc.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.donghoc.setHorizontalHeaderItem(3, item)
        self.sodo = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.sodo.setGeometry(QtCore.QRect(230, 270, 91, 41))
        self.sodo.setMinimum(1)
        self.sodo.setMaximum(10)
        self.sodo.setObjectName("sodo")
        self.goc1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.goc1.setGeometry(QtCore.QRect(910, 60, 63, 51))
        self.goc1.setText("")
        self.goc1.setObjectName("goc1")
        self.goc4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.goc4.setGeometry(QtCore.QRect(910, 240, 63, 51))
        self.goc4.setText("")
        self.goc4.setObjectName("goc4")
        self.DES2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.DES2.setGeometry(QtCore.QRect(770, 120, 121, 51))
        self.DES2.setObjectName("DES2")
        self.textEdit_6 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_6.setGeometry(QtCore.QRect(480, 70, 131, 41))
        self.textEdit_6.setObjectName("textEdit_6")
        self.INC3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.INC3.setGeometry(QtCore.QRect(640, 180, 121, 51))
        self.INC3.setObjectName("INC3")
        self.DES4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.DES4.setGeometry(QtCore.QRect(770, 240, 121, 51))
        self.DES4.setObjectName("DES4")
        self.DES1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.DES1.setGeometry(QtCore.QRect(770, 60, 121, 51))
        self.DES1.setObjectName("DES1")
        self.textEdit_3 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(480, 250, 131, 41))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(480, 190, 131, 41))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_7 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_7.setGeometry(QtCore.QRect(670, 20, 201, 21))
        self.textEdit_7.setObjectName("textEdit_7")
        self.goc2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.goc2.setGeometry(QtCore.QRect(910, 120, 63, 51))
        self.goc2.setText("")
        self.goc2.setObjectName("goc2")
        self.DES3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.DES3.setGeometry(QtCore.QRect(770, 180, 121, 51))
        self.DES3.setObjectName("DES3")
        self.textEdit_5 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(480, 130, 131, 41))
        self.textEdit_5.setObjectName("textEdit_5")
        self.INC2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.INC2.setGeometry(QtCore.QRect(640, 120, 121, 51))
        self.INC2.setObjectName("INC2")
        self.INC4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.INC4.setGeometry(QtCore.QRect(640, 240, 121, 51))
        self.INC4.setObjectName("INC4")
        self.goc3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.goc3.setGeometry(QtCore.QRect(910, 180, 63, 51))
        self.goc3.setText("")
        self.goc3.setObjectName("goc3")
        self.INC1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.INC1.setGeometry(QtCore.QRect(640, 60, 121, 51))
        self.INC1.setObjectName("INC1")
        self.tocdo = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.tocdo.setGeometry(QtCore.QRect(230, 320, 91, 41))
        self.tocdo.setMinimum(100)
        self.tocdo.setMaximum(2000)
        self.tocdo.setObjectName("tocdo")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 270, 191, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_8 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_8.setGeometry(QtCore.QRect(10, 320, 191, 41))
        self.textEdit_8.setObjectName("textEdit_8")
        self.textEdit_9 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_9.setGeometry(QtCore.QRect(10, 370, 351, 311))
        self.textEdit_9.setObjectName("textEdit_9")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1234, 26))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.ZD.setText(_translate("mainWindow", "Z+"))
        self.XT.setText(_translate("mainWindow", "X-"))
        self.XD.setText(_translate("mainWindow", "X+"))
        self.ZT.setText(_translate("mainWindow", "Z-"))
        self.O.setText(_translate("mainWindow", "HOME"))
        self.textEdit.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:700; color:#000000; background-color:#ffffff;\">POSITION CONTROL</span></p></body></html>"))
        self.DES2.setText(_translate("mainWindow", "DES"))
        self.textEdit_6.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Khớp 1</span></p></body></html>"))
        self.INC3.setText(_translate("mainWindow", "INC"))
        self.DES4.setText(_translate("mainWindow", "DES"))
        self.DES1.setText(_translate("mainWindow", "DES"))
        self.textEdit_3.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Khớp 4</span></p></body></html>"))
        self.textEdit_4.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Khớp 3</span></p></body></html>"))
        self.textEdit_7.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:700; color:#000000; background-color:#ffffff;\">JOIN CONTROL</span></p></body></html>"))
        self.DES3.setText(_translate("mainWindow", "DES"))
        self.textEdit_5.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Khớp 2</span></p></body></html>"))
        self.INC2.setText(_translate("mainWindow", "INC"))
        self.INC4.setText(_translate("mainWindow", "INC"))
        self.INC1.setText(_translate("mainWindow", "INC"))
        self.textEdit_2.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Bước duy chuyển</span></p></body></html>"))
        self.textEdit_8.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Tốc độ duy chuyển</span></p></body></html>"))
        self.textEdit_9.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">note:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">- Bước duy chuyển ( độ )</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">VD: bước duy chuyển = 1 =&gt; mỗi lần duy chuyển các khớp quay 1 độ.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">- Tốc độ duy chuyển ( ms ) </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">VD: 100 ms , mỗi bước động cơ quay trong khoảng thời gian 100ms ( 0,1s )</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec())
