# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_robot_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 694)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(100, 20, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.btn_pos_z_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pos_z_plus.setGeometry(QtCore.QRect(160, 50, 81, 31))
        self.btn_pos_z_plus.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_pos_z_plus.setObjectName("btn_pos_z_plus")
        self.btn_pos_x_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pos_x_minus.setGeometry(QtCore.QRect(260, 50, 81, 31))
        self.btn_pos_x_minus.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_pos_x_minus.setObjectName("btn_pos_x_minus")
        self.btn_pos_home = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pos_home.setGeometry(QtCore.QRect(160, 90, 81, 31))
        self.btn_pos_home.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_pos_home.setObjectName("btn_pos_home")
        self.btn_pos_x_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pos_x_plus.setGeometry(QtCore.QRect(60, 130, 81, 31))
        self.btn_pos_x_plus.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_pos_x_plus.setObjectName("btn_pos_x_plus")
        self.btn_pos_z_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pos_z_minus.setGeometry(QtCore.QRect(160, 130, 81, 31))
        self.btn_pos_z_minus.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_pos_z_minus.setObjectName("btn_pos_z_minus")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 180, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 360, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_gripper_on = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gripper_on.setGeometry(QtCore.QRect(200, 350, 81, 41))
        self.btn_gripper_on.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_gripper_on.setObjectName("btn_gripper_on")
        self.btn_home = QtWidgets.QPushButton(self.centralwidget)
        self.btn_home.setGeometry(QtCore.QRect(90, 420, 81, 41))
        self.btn_home.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_home.setObjectName("btn_home")
        self.btn_setting = QtWidgets.QPushButton(self.centralwidget)
        self.btn_setting.setGeometry(QtCore.QRect(200, 420, 81, 41))
        self.btn_setting.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_setting.setObjectName("btn_setting")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 490, 441, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.table_tmatrix = QtWidgets.QTableWidget(self.centralwidget)
        self.table_tmatrix.setGeometry(QtCore.QRect(0, 520, 421, 121))
        self.table_tmatrix.setAutoScroll(True)
        self.table_tmatrix.setRowCount(4)
        self.table_tmatrix.setColumnCount(4)
        self.table_tmatrix.setObjectName("table_tmatrix")
        self.table_tmatrix.horizontalHeader().setVisible(False)
        self.table_tmatrix.horizontalHeader().setHighlightSections(False)
        self.table_tmatrix.horizontalHeader().setStretchLastSection(False)
        self.table_tmatrix.verticalHeader().setVisible(False)
        self.table_tmatrix.verticalHeader().setHighlightSections(False)
        self.table_tmatrix.verticalHeader().setStretchLastSection(False)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 210, 348, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.line_j1_val = QtWidgets.QLineEdit(self.widget)
        self.line_j1_val.setReadOnly(True)
        self.line_j1_val.setObjectName("line_j1_val")
        self.horizontalLayout.addWidget(self.line_j1_val)
        self.btn_j1_inc = QtWidgets.QPushButton(self.widget)
        self.btn_j1_inc.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_j1_inc.setObjectName("btn_j1_inc")
        self.horizontalLayout.addWidget(self.btn_j1_inc)
        self.btn_j1_des = QtWidgets.QPushButton(self.widget)
        self.btn_j1_des.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_j1_des.setObjectName("btn_j1_des")
        self.horizontalLayout.addWidget(self.btn_j1_des)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(30, 240, 348, 25))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.line_j2_val = QtWidgets.QLineEdit(self.widget1)
        self.line_j2_val.setReadOnly(True)
        self.line_j2_val.setObjectName("line_j2_val")
        self.horizontalLayout_2.addWidget(self.line_j2_val)
        self.btn_j2_inc = QtWidgets.QPushButton(self.widget1)
        self.btn_j2_inc.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_j2_inc.setObjectName("btn_j2_inc")
        self.horizontalLayout_2.addWidget(self.btn_j2_inc)
        self.btn_j2_des = QtWidgets.QPushButton(self.widget1)
        self.btn_j2_des.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_j2_des.setObjectName("btn_j2_des")
        self.horizontalLayout_2.addWidget(self.btn_j2_des)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(30, 270, 348, 25))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.line_j3_val = QtWidgets.QLineEdit(self.widget2)
        self.line_j3_val.setReadOnly(True)
        self.line_j3_val.setObjectName("line_j3_val")
        self.horizontalLayout_3.addWidget(self.line_j3_val)
        self.btn_j3_inc = QtWidgets.QPushButton(self.widget2)
        self.btn_j3_inc.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_j3_inc.setObjectName("btn_j3_inc")
        self.horizontalLayout_3.addWidget(self.btn_j3_inc)
        self.btn_j3_des = QtWidgets.QPushButton(self.widget2)
        self.btn_j3_des.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_j3_des.setObjectName("btn_j3_des")
        self.horizontalLayout_3.addWidget(self.btn_j3_des)
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(30, 300, 348, 25))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.line_j4_val = QtWidgets.QLineEdit(self.widget3)
        self.line_j4_val.setReadOnly(True)
        self.line_j4_val.setObjectName("line_j4_val")
        self.horizontalLayout_4.addWidget(self.line_j4_val)
        self.btn_j4_inc = QtWidgets.QPushButton(self.widget3)
        self.btn_j4_inc.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_j4_inc.setObjectName("btn_j4_inc")
        self.horizontalLayout_4.addWidget(self.btn_j4_inc)
        self.btn_j4_des = QtWidgets.QPushButton(self.widget3)
        self.btn_j4_des.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}")
        self.btn_j4_des.setObjectName("btn_j4_des")
        self.horizontalLayout_4.addWidget(self.btn_j4_des)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "POSITION CONTROL"))
        self.btn_pos_z_plus.setText(_translate("MainWindow", "↑ Z+"))
        self.btn_pos_x_minus.setText(_translate("MainWindow", "X- ↗"))
        self.btn_pos_home.setText(_translate("MainWindow", "O"))
        self.btn_pos_x_plus.setText(_translate("MainWindow", "X+ ↙"))
        self.btn_pos_z_minus.setText(_translate("MainWindow", "↓ Z-"))
        self.label_3.setText(_translate("MainWindow", "JOIN CONTROL"))
        self.label.setText(_translate("MainWindow", "GRIPPER"))
        self.btn_gripper_on.setText(_translate("MainWindow", "ON"))
        self.btn_home.setText(_translate("MainWindow", "HOME"))
        self.btn_setting.setText(_translate("MainWindow", "SETTING"))
        self.label_2.setText(_translate("MainWindow", "HOMOGENEOUS TRANSFORMATION MATRICES"))
        self.label_5.setText(_translate("MainWindow", "Join 1"))
        self.btn_j1_inc.setText(_translate("MainWindow", "INC ↑"))
        self.btn_j1_des.setText(_translate("MainWindow", "DES ↓"))
        self.label_6.setText(_translate("MainWindow", "Join 2"))
        self.btn_j2_inc.setText(_translate("MainWindow", "INC ↑"))
        self.btn_j2_des.setText(_translate("MainWindow", "DES ↓"))
        self.label_7.setText(_translate("MainWindow", "Join 3"))
        self.btn_j3_inc.setText(_translate("MainWindow", "INC ↑"))
        self.btn_j3_des.setText(_translate("MainWindow", "DES ↓"))
        self.label_8.setText(_translate("MainWindow", "Join 4"))
        self.btn_j4_inc.setText(_translate("MainWindow", "INC ↑"))
        self.btn_j4_des.setText(_translate("MainWindow", "DES ↓"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
